// Writes assets/audio/manifest.js: the SFX + voice manifests wrapped in a classic <script>
// global, so audition.html can read them over file:// (where fetch() of JSON is blocked).
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

export async function writeAuditionData(audioDir) {
  const read = async (rel) => {
    try {
      return JSON.parse(await readFile(path.join(audioDir, rel), 'utf8'));
    } catch {
      return null;
    }
  };
  const data = {
    generatedAt: new Date().toISOString(),
    sfx: await read('sfx/manifest.json'),
    voices: await read('voices/manifest.json'),
  };
  const js = `// Generated by tools/sound-factory (render.mjs / blips.mjs / speak.mjs). Do not edit.\nwindow.STUDYGOTCHI_AUDIO = ${JSON.stringify(data)};\n`;
  const out = path.join(audioDir, 'manifest.js');
  await writeFile(out, js);
  return out;
}
