/**
 * Names for everything the audio kit can play, and the small tables that tie sound to the
 * world: which voice a biome speaks with, which bed a biome plays, which sound an event fires.
 *
 * Files live under /assets/audio (a symlink to the repo's assets/audio). SFX and voices are
 * generated by tools/sound-factory; music is third-party CC0 / CC-BY and every track here
 * carries the credit line its license asks for (full list: assets/audio/music/CREDITS.md).
 */

import type { BiomeId, CharacterState } from "@/lib/world/types";
import type { VoiceMood } from "./schedule.ts";

export type { VoiceMood };

export const AUDIO_BASE = "/assets/audio";

// ---------- sound effects (tools/sound-factory/render.mjs; assets/audio/sfx/manifest.json) ----------

export const SFX_NAMES = [
  "ui-tap",
  "ui-confirm",
  "ui-cancel",
  "ui-hover",
  "card-open",
  "card-close",
  "sprout-appear",
  "landmark-build-1",
  "landmark-build-2",
  "landmark-build-3",
  "landmark-upgrade",
  "creature-arrive",
  "creature-tap",
  "creature-happy",
  "creature-sad",
  "creature-sleep",
  "creature-greet",
  "evidence-ingested",
  "progress-tick",
  "progress-streak",
  "progress-level-up",
  "camera-dive",
  "camera-rise",
  "visit-whoosh",
  "error-soft",
  "explode-comic",
  "recover-chime",
  "ambient-wind-gust",
  "ambient-bird-chirp",
  "space-enter",
  "star-select",
  "lens-weak",
  "cluster-glide",
] as const;

export type SfxName = (typeof SFX_NAMES)[number];

export function sfxFile(name: SfxName): string {
  return `${AUDIO_BASE}/sfx/${name}.wav`;
}

// ---------- voices (tools/sound-factory/blips.mjs; assets/audio/voices/manifest.json) ----------

export const VOICE_SPECIES = ["peach", "coral", "mint", "olive", "lilac"] as const;
export type VoiceSpecies = (typeof VOICE_SPECIES)[number];

export const VOICE_LETTERS = "abcdefghijklmnopqrstuvwxyz";

export function voiceFile(species: VoiceSpecies, letter: string): string {
  return `${AUDIO_BASE}/voices/${species}/${letter}.wav`;
}

/**
 * One voice per creature accent, the way the factory paints them. Until a character carries
 * its own accent, the biome default in lib/world/layout.ts decides.
 */
export const ACCENT_VOICE: Record<string, VoiceSpecies> = {
  "#f2a86f": "peach",
  "#e88a8a": "coral",
  "#8fc9d8": "mint",
  "#b9c96f": "olive",
  "#c9a2e6": "lilac",
};

export const BIOME_VOICE: Record<BiomeId, VoiceSpecies> = {
  forest: "peach",
  city: "coral",
  ice: "mint",
  sand: "olive",
  meadow: "lilac",
};

export function voiceFor(biome: BiomeId, accentHex?: string): VoiceSpecies {
  return (accentHex && ACCENT_VOICE[accentHex.toLowerCase()]) || BIOME_VOICE[biome];
}

export const MOOD_FOR_STATE: Record<CharacterState, VoiceMood> = {
  idle: "neutral",
  evolved: "happy",
  recovered: "happy",
  exploded: "sad",
  faded: "sad",
};

// ---------- music (assets/audio/music/catalog.json, shortlisted) ----------

export interface BgmTrack {
  id: string;
  title: string;
  artist: string;
  license: string;
  /** the exact line the license asks us to show */
  credit: string;
  source: string;
  file: string;
  /** trim for beds that sit under speech and SFX; 1 = as mastered */
  gain: number;
}

const track = (t: Omit<BgmTrack, "gain"> & { gain?: number }): BgmTrack => ({ gain: 1, ...t });

export const BGM = {
  "8bit-bossa": track({
    id: "8bit-bossa",
    title: "8bit Bossa",
    artist: "Joth",
    license: "CC0",
    credit: "8bit Bossa by Joth (opengameart.org), CC0",
    source: "https://opengameart.org/content/bossa-nova",
    file: `${AUDIO_BASE}/music/tracks/8bit-bossa.mp3`,
    gain: 0.75,
  }),
  headscratcher: track({
    id: "headscratcher",
    title: "Headscratcher",
    artist: "congusbongus",
    license: "CC-BY 4.0",
    credit: "Headscratcher by congusbongus (opengameart.org), CC-BY 4.0",
    source: "https://opengameart.org/content/headscratcher",
    file: `${AUDIO_BASE}/music/tracks/headscratcher.mp3`,
    gain: 0.7,
  }),
  "ukulele-forest-loop": track({
    id: "ukulele-forest-loop",
    title: "Ukulele Forest",
    artist: "StarNinjas",
    license: "CC0",
    credit: "Ukulele Forest by StarNinjas (opengameart.org), CC0",
    source: "https://opengameart.org/content/ukulele-forest-beginning-loop-and-end",
    file: `${AUDIO_BASE}/music/tracks/ukulele-forest-loop.mp3`,
    gain: 0.8,
  }),
  "forest-ambience": track({
    id: "forest-ambience",
    title: "Forest Ambience",
    artist: "TinyWorlds",
    license: "CC0",
    credit: "Forest Ambience by TinyWorlds (opengameart.org), CC0",
    source: "https://opengameart.org/content/forest-ambience",
    file: `${AUDIO_BASE}/music/tracks/forest-ambience.mp3`,
    gain: 0.35,
  }),
  "cozy-puzzle-1": track({
    id: "cozy-puzzle-1",
    title: "Cozy Puzzle In-Game 1",
    artist: "MintoDog",
    license: "CC0",
    credit: "Cozy Puzzle In-Game 1 by MintoDog (opengameart.org), CC0",
    source: "https://opengameart.org/content/cozy-puzzle-in-game-1",
    file: `${AUDIO_BASE}/music/tracks/cozy-puzzle-1.mp3`,
    gain: 0.7,
  }),
  "wintery-loop": track({
    id: "wintery-loop",
    title: "Wintery loop",
    artist: "Emma_MA",
    license: "CC0",
    credit: "Wintery loop by Emma_MA (opengameart.org), CC0",
    source: "https://opengameart.org/content/wintery-loop",
    file: `${AUDIO_BASE}/music/tracks/wintery-loop.mp3`,
    gain: 0.7,
  }),
  "lobby-time": track({
    id: "lobby-time",
    title: "Lobby Time",
    artist: "Kevin MacLeod",
    license: "CC-BY 3.0",
    credit: "Lobby Time by Kevin MacLeod (incompetech.com), licensed under Creative Commons: By Attribution 3.0",
    source: "https://incompetech.com/music/royalty-free/",
    file: `${AUDIO_BASE}/music/tracks/lobby-time.mp3`,
    gain: 0.65,
  }),
  "bassa-island": track({
    id: "bassa-island",
    title: "Bassa Island Game Loop",
    artist: "Kevin MacLeod",
    license: "CC-BY 3.0",
    credit: "Bassa Island Game Loop by Kevin MacLeod (incompetech.com), licensed under Creative Commons: By Attribution 3.0",
    source: "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100840",
    file: `${AUDIO_BASE}/music/tracks/bassa-island.mp3`,
    gain: 0.65,
  }),
  sleepy: track({
    id: "sleepy",
    title: "Sleepy",
    artist: "congusbongus",
    license: "CC-BY 4.0",
    credit: "Sleepy by congusbongus (opengameart.org), CC-BY 4.0",
    source: "https://opengameart.org/content/sleepy-0",
    file: `${AUDIO_BASE}/music/tracks/sleepy.mp3`,
    gain: 0.6,
  }),
  wallpaper: track({
    id: "wallpaper",
    title: "Wallpaper",
    artist: "Kevin MacLeod",
    license: "CC-BY 3.0",
    credit: "Wallpaper by Kevin MacLeod (incompetech.com), licensed under Creative Commons: By Attribution 3.0",
    source: "https://incompetech.com/music/royalty-free/",
    file: `${AUDIO_BASE}/music/tracks/wallpaper.mp3`,
    gain: 0.55,
  }),
  "shopping-theme": track({
    id: "shopping-theme",
    title: "Shopping Theme",
    artist: "Paranoid",
    license: "CC-BY 3.0",
    credit: "Shopping Theme by Paranoid, via nlhoang162 (opengameart.org), CC-BY 3.0",
    source: "https://opengameart.org/content/shopping-theme",
    file: `${AUDIO_BASE}/music/tracks/shopping-theme.mp3`,
    gain: 0.65,
  }),
  "cutie-pie": track({
    id: "cutie-pie",
    title: "Cutie Pie",
    artist: "FrancisLeeMusic",
    license: "CC-BY 3.0",
    credit: "Cutie Pie by FrancisLeeMusic (opengameart.org), CC-BY 3.0",
    source: "https://opengameart.org/content/cutie-pie",
    file: `${AUDIO_BASE}/music/tracks/cutie-pie.mp3`,
    gain: 0.7,
  }),
  "samba-isobel": track({
    id: "samba-isobel",
    title: "Samba Isobel",
    artist: "Kevin MacLeod",
    license: "CC-BY 3.0",
    credit: "Samba Isobel by Kevin MacLeod (incompetech.com), licensed under Creative Commons: By Attribution 3.0",
    source: "https://incompetech.com/music/royalty-free/",
    file: `${AUDIO_BASE}/music/tracks/samba-isobel.mp3`,
    gain: 0.62,
  }),
  "snow-globe": track({
    id: "snow-globe",
    title: "Snow Globe",
    artist: "Bobjt",
    license: "CC0",
    credit: "Snow Globe by Bobjt (opengameart.org), CC0",
    source: "https://opengameart.org/content/snow-globe",
    file: `${AUDIO_BASE}/music/tracks/snow-globe.mp3`,
    gain: 0.68,
  }),
  "information-astral-bossa": track({
    id: "information-astral-bossa",
    title: "Lunar shop",
    artist: "glitchart",
    license: "CC-BY 4.0",
    credit:
      "Lunar shop by glitchart (opengameart.org), CC-BY 4.0; remixing Lunar Echo (Trevor Lentz), Shop Theme (CleytonKauffman), GoodNight - Lofi (migfus20) and Cutie Pie (FrancisLeeMusic). Cut to a 72-bar loop.",
    source: "https://opengameart.org/content/lunar-shop-trevor-lentz-cleyton-kauffman-migfus-francisleemusic",
    file: `${AUDIO_BASE}/music/tracks/information-astral-bossa.mp3`,
    gain: 0.62,
  }),
} as const satisfies Record<string, BgmTrack>;

export type BgmId = keyof typeof BGM;

export const GLOBE_BGM: BgmId = "cutie-pie";

/** The Information tab: the globe theme, remixed into orbit. Same bossa, airier. */
export const SPACE_BGM: BgmId = "information-astral-bossa";

export const BGM_FOR_BIOME: Record<BiomeId, BgmId> = {
  forest: "ukulele-forest-loop",
  meadow: "cozy-puzzle-1",
  ice: "snow-globe",
  city: "lobby-time",
  sand: "bassa-island",
};

export const NIGHT_BGM_FOR_BIOME: Record<BiomeId, BgmId> = {
  forest: "wallpaper",
  meadow: "wallpaper",
  ice: "wallpaper",
  city: "sleepy",
  sand: "wallpaper",
};

/** A quiet layer under the bed, not a song. */
export const AMBIENCE_FOR_BIOME: Partial<Record<BiomeId, BgmId>> = {
  forest: "forest-ambience",
};

/** How far the music drops while a creature talks. */
export const DUCK_RATIO = 0.35;
export const CROSSFADE_MS = 600;

/** Every bed the website can actually play, for the in-chrome credits list. */
export function usedBgmTracks(): BgmTrack[] {
  const ids = new Set<BgmId>([
    GLOBE_BGM,
    SPACE_BGM,
    ...Object.values(BGM_FOR_BIOME),
    ...Object.values(NIGHT_BGM_FOR_BIOME),
    ...Object.values(AMBIENCE_FOR_BIOME),
  ]);
  return [...ids]
    .map((id) => BGM[id])
    .sort((a, b) => a.artist.localeCompare(b.artist) || a.title.localeCompare(b.title));
}

export const FULL_CREDITS_HREF = `${AUDIO_BASE}/music/CREDITS.md`;
