/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses Endpoint */
        get: operations["list_courses_endpoint_api_courses_get"];
        put?: never;
        /** Create Course Endpoint */
        post: operations["create_course_endpoint_api_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Endpoint */
        get: operations["get_course_endpoint_api_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/concepts/{concept_id}/why": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Concept */
        get: operations["course_concept_api_courses__course_id__concepts__concept_id__why_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/concepts/{concept_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Concept */
        get: operations["course_concept_api_courses__course_id__concepts__concept_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/concepts/{concept_id}/why": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Student Concept */
        get: operations["student_concept_api_courses__course_id__students__student_id__concepts__concept_id__why_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/concepts/{concept_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Student Concept */
        get: operations["student_concept_api_courses__course_id__students__student_id__concepts__concept_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/resources/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Course Resource Endpoint */
        post: operations["ingest_course_resource_endpoint_api_courses__course_id__resources_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/resources/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Student Resource Endpoint */
        post: operations["ingest_student_resource_endpoint_api_courses__course_id__students__student_id__resources_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resources Endpoint */
        get: operations["list_resources_endpoint_api_courses__course_id__resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Student Resources Endpoint */
        get: operations["list_student_resources_endpoint_api_courses__course_id__students__student_id__resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student Resource Endpoint */
        get: operations["get_student_resource_endpoint_api_courses__course_id__students__student_id__resources__resource_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/ontology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ontology Endpoint */
        get: operations["get_ontology_endpoint_api_courses__course_id__ontology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/knowledge-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Graph Endpoint */
        get: operations["get_knowledge_graph_endpoint_api_courses__course_id__students__student_id__knowledge_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Understanding Endpoint */
        get: operations["get_understanding_endpoint_api_courses__course_id__students__student_id__overlay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/mastery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Understanding Endpoint */
        get: operations["get_understanding_endpoint_api_courses__course_id__students__student_id__mastery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/understanding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Understanding Endpoint */
        get: operations["get_understanding_endpoint_api_courses__course_id__students__student_id__understanding_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gaps Endpoint */
        get: operations["get_gaps_endpoint_api_courses__course_id__students__student_id__gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/study-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Study Plan Endpoint */
        post: operations["post_study_plan_endpoint_api_courses__course_id__students__student_id__study_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/world": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get World */
        get: operations["get_world_api_courses__course_id__students__student_id__world_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/world-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** World Events */
        get: operations["world_events_api_courses__course_id__students__student_id__world_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/debug/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_courses__course_id__debug_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/debug/resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resource Debug */
        get: operations["resource_debug_api_courses__course_id__debug_resources__resource_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactType
         * @enum {string}
         */
        ArtifactType: "lecture" | "reading" | "syllabus" | "study_guide" | "homework" | "quiz" | "exam" | "solution_key" | "student_notes" | "classmate_notes" | "worked_solution" | "handwritten_work" | "photo" | "other";
        /** Body_ingest_course_resource_endpoint_api_courses__course_id__resources_ingest_post */
        Body_ingest_course_resource_endpoint_api_courses__course_id__resources_ingest_post: {
            origin: components["schemas"]["SourceOrigin"];
            artifact_type: components["schemas"]["ArtifactType"];
            /** File */
            file: string;
        };
        /** Body_ingest_student_resource_endpoint_api_courses__course_id__students__student_id__resources_ingest_post */
        Body_ingest_student_resource_endpoint_api_courses__course_id__students__student_id__resources_ingest_post: {
            origin: components["schemas"]["SourceOrigin"];
            artifact_type: components["schemas"]["ArtifactType"];
            /** File */
            file: string;
        };
        /** CitationOut */
        CitationOut: {
            /** Chunk Id */
            chunk_id?: string | null;
            /** Page Number */
            page_number?: number | null;
            /** Snippet */
            snippet?: string | null;
            /** Link Type */
            link_type: string;
        };
        /** ConceptAssessmentOut */
        ConceptAssessmentOut: {
            /**
             * Assessment Id
             * Format: uuid
             */
            assessment_id: string;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Title */
            title: string;
            /** Label */
            label: string;
        };
        /**
         * ConceptDetailResponse
         * @description Everything an inspector shows about one concept: the student's evidence,
         *     the files that teach it (ranked, deduplicated), relationships, and the
         *     assessment items that test it.
         */
        ConceptDetailResponse: {
            /**
             * Concept Id
             * Format: uuid
             */
            concept_id: string;
            /** Name */
            name: string;
            /** Definition */
            definition?: string | null;
            /** Scope */
            scope: string;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Resources */
            resources: components["schemas"]["ConceptResourceOut"][];
            /** Relationships */
            relationships?: components["schemas"]["ConceptRelationshipOut"][];
            /** Assessments */
            assessments?: components["schemas"]["ConceptAssessmentOut"][];
            /**
             * Suppressed Resource Count
             * @default 0
             */
            suppressed_resource_count: number;
        };
        /** ConceptEdgeOut */
        ConceptEdgeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Concept Id
             * Format: uuid
             */
            source_concept_id: string;
            /**
             * Target Concept Id
             * Format: uuid
             */
            target_concept_id: string;
            edge_type: components["schemas"]["ConceptEdgeType"];
            /** Confidence */
            confidence: number;
            /** Authority Weight */
            authority_weight: number;
            /** Status */
            status: string;
            /**
             * Is Redundant In Display Graph
             * @default false
             */
            is_redundant_in_display_graph: boolean;
        };
        /**
         * ConceptEdgeType
         * @enum {string}
         */
        ConceptEdgeType: "PREREQUISITE_FOR" | "RELATED_TO" | "BUILDS_ON" | "EXAMPLE_OF" | "APPLICATION_OF" | "CONTRASTS_WITH";
        /**
         * ConceptKind
         * @enum {string}
         */
        ConceptKind: "principle" | "definition" | "theorem" | "method" | "procedure" | "skill" | "model" | "formula" | "application" | "topic_cluster";
        /** ConceptOut */
        ConceptOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Short Definition */
            short_definition: string | null;
            concept_kind: components["schemas"]["ConceptKind"];
            granularity: components["schemas"]["Granularity"];
            /** Importance */
            importance: number;
            scope: components["schemas"]["ConceptScope"];
        };
        /** ConceptRelationshipOut */
        ConceptRelationshipOut: {
            /**
             * Source
             * Format: uuid
             */
            source: string;
            /**
             * Target
             * Format: uuid
             */
            target: string;
            /** Edge Type */
            edge_type: string;
            /** Status */
            status: string;
            /** Confidence */
            confidence: number;
            /** Resource Id */
            resource_id?: string | null;
            /** Page Number */
            page_number?: number | null;
            /** Snippet */
            snippet?: string | null;
        };
        /**
         * ConceptResourceOut
         * @description A file that teaches or assesses the concept, with where in it.
         */
        ConceptResourceOut: {
            resource: components["schemas"]["ResourceOut"];
            /** Link Type */
            link_type: string;
            /** Depth Score */
            depth_score: number;
            /** Rank Score */
            rank_score?: number | null;
            /** Novelty */
            novelty?: number | null;
            /** Citations */
            citations?: components["schemas"]["CitationOut"][];
        };
        /**
         * ConceptScope
         * @enum {string}
         */
        ConceptScope: "course" | "personal" | "shared_extension";
        /**
         * ConceptState
         * @enum {string}
         */
        ConceptState: "frontier" | "exposed" | "uncertain" | "struggling" | "developing" | "strong" | "mastered" | "fragile" | "stale";
        /** CourseCreateRequest */
        CourseCreateRequest: {
            /** Name */
            name: string;
            /** Code */
            code?: string | null;
            /** Term */
            term?: string | null;
        };
        /** CourseOut */
        CourseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string | null;
            /** Term */
            term: string | null;
        };
        /**
         * DiscoveryState
         * @enum {string}
         */
        DiscoveryState: "unseen" | "frontier" | "encountered" | "active";
        /**
         * EvidenceOut
         * @description One evidence event behind a concept's understanding.
         */
        EvidenceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Evidence Type */
            evidence_type: string;
            /** Outcome */
            outcome: number | null;
            /** Strength */
            strength: number;
            /** Certainty */
            certainty: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            resource?: components["schemas"]["ResourceOut"] | null;
            /** Assessment Item Id */
            assessment_item_id?: string | null;
        };
        /**
         * GapAction
         * @enum {string}
         */
        GapAction: "study" | "diagnose" | "review" | "optional";
        /** GapOut */
        GapOut: {
            /**
             * Concept Id
             * Format: uuid
             */
            concept_id: string;
            /** Name */
            name: string;
            /** Understanding */
            understanding: number;
            /** Priority */
            priority: number;
            action: components["schemas"]["GapAction"];
            /** Reason */
            reason: string;
        };
        /** GapsResponse */
        GapsResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Target Concept Id */
            target_concept_id: string | null;
            /** Target Assessment Id */
            target_assessment_id: string | null;
            /** Gaps */
            gaps: components["schemas"]["GapOut"][];
        };
        /**
         * Granularity
         * @enum {string}
         */
        Granularity: "cluster" | "core" | "atomic";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeOut */
        MeOut: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Courses */
            courses: components["schemas"]["CourseOut"][];
        };
        /** OntologyResponse */
        OntologyResponse: {
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Concepts */
            concepts: components["schemas"]["ConceptOut"][];
            /** Edges */
            edges: components["schemas"]["ConceptEdgeOut"][];
        };
        /** PersonalGraphEdgeOut */
        PersonalGraphEdgeOut: {
            /**
             * Source
             * Format: uuid
             */
            source: string;
            /**
             * Target
             * Format: uuid
             */
            target: string;
            /** Edge Type */
            edge_type: string;
            /** Origin */
            origin: string;
            /** Confidence */
            confidence: number;
        };
        /** PersonalGraphNodeOut */
        PersonalGraphNodeOut: {
            /**
             * Concept Id
             * Format: uuid
             */
            concept_id: string;
            /** Name */
            name: string;
            scope: components["schemas"]["ConceptScope"];
            discovery_state: components["schemas"]["DiscoveryState"];
            /** Importance */
            importance: number;
            /** Personal Relevance */
            personal_relevance: number;
            /** Understanding */
            understanding: number | null;
            /** Mastery */
            mastery: number | null;
            /** Familiarity */
            familiarity: number;
            /** Confidence */
            confidence: number;
            /** Readiness */
            readiness: number;
            /** Fragility */
            fragility: number;
            state: components["schemas"]["ConceptState"];
            /** Cluster Id */
            cluster_id?: string | null;
            /** Cluster */
            cluster?: string | null;
        };
        /** PersonalGraphResponse */
        PersonalGraphResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Nodes */
            nodes: components["schemas"]["PersonalGraphNodeOut"][];
            /** Edges */
            edges: components["schemas"]["PersonalGraphEdgeOut"][];
            /** Hidden Concept Count */
            hidden_concept_count: number;
            /**
             * Graph Version
             * @default
             */
            graph_version: string;
        };
        /** ResourceIngestResponse */
        ResourceIngestResponse: {
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /** Status */
            status: string;
            /** Concepts Created */
            concepts_created: number;
            /** Concepts Merged */
            concepts_merged: number;
            /** Edges Created */
            edges_created: number;
            /**
             * Assessment Items Created
             * @default 0
             */
            assessment_items_created: number;
            /** Child Count */
            child_count?: number | null;
            /** Child Failures */
            child_failures?: string[];
        };
        /**
         * ResourceOut
         * @description One ingested file, for the Files view.
         */
        ResourceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Origin */
            origin: string;
            /** Artifact Type */
            artifact_type: string;
            /** Status */
            status: string;
            /** Concept Count */
            concept_count: number;
            /** Concept Ids */
            concept_ids?: string[];
            /** Created At */
            created_at?: string | null;
        };
        /** ResourceStatusOut */
        ResourceStatusOut: {
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /** Title */
            title: string;
            /** Origin */
            origin: string;
            /** Artifact Type */
            artifact_type: string;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /** Phase A Ms */
            phase_a_ms?: number | null;
            /** Phase B Ms */
            phase_b_ms?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SourceOrigin
         * @enum {string}
         */
        SourceOrigin: "instructor" | "ta" | "student_self" | "classmate" | "external";
        /** StudentResourceIngestResponse */
        StudentResourceIngestResponse: {
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /** Status */
            status: string;
            /** Evidence Events Created */
            evidence_events_created: number;
            /** Concepts Touched */
            concepts_touched: string[];
            /**
             * Personal Concepts Created
             * @default 0
             */
            personal_concepts_created: number;
            /**
             * Analysis
             * @default none
             */
            analysis: string;
            /** Child Count */
            child_count?: number | null;
            /** Child Failures */
            child_failures?: string[];
        };
        /** StudyPlanRequest */
        StudyPlanRequest: {
            /** Target Concept Id */
            target_concept_id?: string | null;
            /** Assessment Id */
            assessment_id?: string | null;
        };
        /** StudyPlanResponse */
        StudyPlanResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /**
             * Target Concept Id
             * Format: uuid
             */
            target_concept_id: string;
            /** Gaps */
            gaps: components["schemas"]["GapOut"][];
            /**
             * Study Order
             * @description Concept IDs in recommended study order.
             */
            study_order: string[];
        };
        /** UnderstandingEntryOut */
        UnderstandingEntryOut: {
            /**
             * Concept Id
             * Format: uuid
             */
            concept_id: string;
            /** Name */
            name: string;
            discovery_state: components["schemas"]["DiscoveryState"];
            /** Understanding */
            understanding: number | null;
            /** Positive Evidence */
            positive_evidence: number;
            /** Negative Evidence */
            negative_evidence: number;
            /** Last Evidence At */
            last_evidence_at: string | null;
            /** Last Practiced At */
            last_practiced_at: string | null;
        };
        /** UnderstandingResponse */
        UnderstandingResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Concepts */
            concepts: components["schemas"]["UnderstandingEntryOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorldEventKind
         * @enum {string}
         */
        WorldEventKind: "RESOURCE_ADDED" | "RESOURCE_ANALYZED" | "CONCEPT_DISCOVERED" | "FRONTIER_EXPANDED" | "UNDERSTANDING_GAIN" | "UNDERSTANDING_DROP" | "CONCEPT_MASTERED";
        /** WorldEventOut */
        WorldEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            event: components["schemas"]["WorldEventKind"];
            /** Concept Id */
            concept_id?: string | null;
            /** Resource Id */
            resource_id?: string | null;
            /** Delta */
            delta?: number | null;
            /** Explanation */
            explanation: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WorldEventsResponse */
        WorldEventsResponse: {
            /** Events */
            events: components["schemas"]["WorldEventOut"][];
        };
        /** WorldRegionOut */
        WorldRegionOut: {
            /**
             * Concept Id
             * Format: uuid
             */
            concept_id: string;
            /** Name */
            name: string;
            /** Cluster Id */
            cluster_id?: string | null;
            /** Cluster */
            cluster?: string | null;
            /** Terrain Height */
            terrain_height: number;
            /** Terrain Area */
            terrain_area: number;
            /** Fog */
            fog: number;
            /**
             * Semantic State
             * @enum {string}
             */
            semantic_state: "frontier" | "exposed" | "struggling" | "developing" | "strong" | "mastered" | "stale";
            /**
             * Creature State
             * @enum {string}
             */
            creature_state: "unhatched" | "weak" | "evolved" | "ascended" | "sleepy" | "normal";
        };
        /** WorldResponse */
        WorldResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** World Version */
            world_version: string;
            /** Regions */
            regions: components["schemas"]["WorldRegionOut"][];
            /** Edges */
            edges: components["schemas"]["PersonalGraphEdgeOut"][];
            /** Hidden Concept Count */
            hidden_concept_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    list_courses_endpoint_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOut"][];
                };
            };
        };
    };
    create_course_endpoint_api_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_endpoint_api_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_concept_api_courses__course_id__concepts__concept_id__why_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                concept_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_concept_api_courses__course_id__concepts__concept_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                concept_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    student_concept_api_courses__course_id__students__student_id__concepts__concept_id__why_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
                concept_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    student_concept_api_courses__course_id__students__student_id__concepts__concept_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
                concept_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_course_resource_endpoint_api_courses__course_id__resources_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_course_resource_endpoint_api_courses__course_id__resources_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_student_resource_endpoint_api_courses__course_id__students__student_id__resources_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_student_resource_endpoint_api_courses__course_id__students__student_id__resources_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResourceIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resources_endpoint_api_courses__course_id__resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_student_resources_endpoint_api_courses__course_id__students__student_id__resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceStatusOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_resource_endpoint_api_courses__course_id__students__student_id__resources__resource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ontology_endpoint_api_courses__course_id__ontology_get: {
        parameters: {
            query?: {
                view?: "canonical" | "reduced";
            };
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OntologyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_graph_endpoint_api_courses__course_id__students__student_id__knowledge_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_understanding_endpoint_api_courses__course_id__students__student_id__overlay_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnderstandingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_understanding_endpoint_api_courses__course_id__students__student_id__mastery_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnderstandingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_understanding_endpoint_api_courses__course_id__students__student_id__understanding_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnderstandingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gaps_endpoint_api_courses__course_id__students__student_id__gaps_get: {
        parameters: {
            query?: {
                target_concept_id?: string | null;
                assessment_id?: string | null;
            };
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_study_plan_endpoint_api_courses__course_id__students__student_id__study_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_world_api_courses__course_id__students__student_id__world_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    world_events_api_courses__course_id__students__student_id__world_events_get: {
        parameters: {
            query?: {
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_courses__course_id__debug_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resource_debug_api_courses__course_id__debug_resources__resource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
